[package]
name          = "tcp-stream"
version       = "0.4.1" # remember to update html_root_url
authors       = ["Marc-Antoine Perennou <Marc-Antoine@Perennou.com>"]
edition       = "2018"
description   = "mio's TcpStream on steroids"
repository    = "https://github.com/Keruspe/tcp-stream"
documentation = "https://docs.rs/tcp-stream"
keywords      = ["tcp", "mio", "io", "async", "non-blocking"]
categories    = ["asynchronous", "network-programming"]
license       = "BSD-2-Clause"

[lib]
name = "tcp_stream"

[features]
default                 = ["native-tls"]
dangerous_configuration = ["rustls-connector/dangerous_configuration"]
quic                    = ["rustls-connector/quic"]
rustls                  = ["rustls-connector"]
tokio                   = ["futures", "tokio-io"]
vendored                = ["openssl/vendored"]

[dependencies]
cfg-if = "^0.1.5"
mio    = { git = "git://github.com/tokio-rs/mio" }

[dependencies.futures]
version  = "^0.1"
optional = true

[dependencies.native-tls]
version  = "^0.2"
optional = true

[dependencies.openssl]
version  = "^0.10"
optional = true

[dependencies.rustls-connector]
version  = "^0.7"
optional = true

[dependencies.tokio-io]
version  = "^0.1.7"
optional = true

[package.metadata.docs.rs]
all-features = true

[badges]
travis-ci = { repository = "Keruspe/tcp-stream" }
appveyor  = { repository = "Keruspe/tcp-stream" }
